# This file is part of helpers4.
# Copyright (C) 2026 helpers4
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Conventional Commits Check
description: Validate commit messages against the Conventional Commits specification
author: helpers4
branding:
  icon: check-circle
  color: blue
inputs:
  checkout:
    description: Run actions/checkout with fetch-depth 0 before validation
    required: false
    default: "true"
  base-sha:
    description: Base commit SHA to compare against (optional if running on push or pull_request)
    required: false
    default: ""
  head-sha:
    description: Head commit SHA to validate (optional if running on push or pull_request)
    required: false
    default: ""
  types:
    description: "Allowed types (pipe-separated) - default: feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
    required: false
    default: "feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
  scopes:
    description: "Allowed scopes (regex patterns, pipe-separated) - empty means all scopes allowed"
    required: false
    default: ""
  require-scope:
    description: "Require a scope in each commit message"
    required: false
    default: "false"
  ignore-commits:
    description: "Patterns to ignore (regex, newline-separated) - e.g., ^Merge branch|^Revert"
    required: false
    default: ""
  validate-pr-title:
    description: "Also validate the PR title against conventional commits format"
    required: false
    default: "false"
  pr-comment:
    description: Comment on PR with validation results (none, error, success, both)
    required: false
    default: "error"
outputs:
  status:
    description: "Validation status: success or failure"
    value: ${{ steps.validate.outputs.status }}
  invalid-count:
    description: "Number of invalid commits"
    value: ${{ steps.validate.outputs.invalid-count }}
  valid-count:
    description: "Number of valid commits"
    value: ${{ steps.validate.outputs.valid-count }}
  error-message:
    description: "Detailed error message if validation failed"
    value: ${{ steps.validate.outputs.error-message }}
runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Validate commit messages
      id: validate
      shell: bash
      env:
        INPUT_BASE_SHA: ${{ inputs.base-sha }}
        INPUT_HEAD_SHA: ${{ inputs.head-sha }}
        INPUT_TYPES: ${{ inputs.types }}
        INPUT_SCOPES: ${{ inputs.scopes }}
        INPUT_REQUIRE_SCOPE: ${{ inputs.require-scope }}
        INPUT_IGNORE_COMMITS: ${{ inputs.ignore-commits }}
        INPUT_VALIDATE_PR_TITLE: ${{ inputs.validate-pr-title }}
        INPUT_PR_COMMENT: ${{ inputs.pr-comment }}
      run: |
        "${{ github.action_path }}/scripts/validate.sh"
