#!/usr/bin/env bash
# This file is part of helpers4.
# Copyright (C) 2025 baxyz
# SPDX-License-Identifier: LGPL-3.0-or-later
set -euo pipefail

JOBS="${INPUT_JOBS:?INPUT_JOBS is required}"
EXTRA_MARKDOWN="${INPUT_EXTRA_MARKDOWN:-}"

if ! echo "$JOBS" | jq -e 'type == "object"' >/dev/null 2>&1; then
  echo "Error: jobs input must be a JSON object, e.g. '{\"Build\": \"success\"}'" >&2
  exit 1
fi

TOTAL=$(echo "$JOBS" | jq 'length')
PASSED=$(echo "$JOBS" | jq '[to_entries[] | select(.value == "success")] | length')

if [[ "$PASSED" -eq "$TOTAL" ]]; then
  BANNER="## ✅ PR Validation Passed

> All checks passed!"
else
  BANNER="## ❌ PR Validation Failed

> ${PASSED}/${TOTAL} checks passed"
fi

ROWS=$(echo "$JOBS" | jq -r '
  to_entries[] |
  (if .value == "success" then "✅"
   elif .value == "failure" then "❌"
   elif .value == "skipped" then "⏭️"
   else "⚠️" end) as $icon |
  (if .value == "success" then "`passing`"
   elif .value == "failure" then "`failing`"
   elif .value == "skipped" then "`skipped`"
   else "`unknown`" end) as $badge |
  "| \($icon) | **\(.key)** | \($badge) |"
')

BODY="${BANNER}

---

### 📋 Pipeline Status

| | Job | Status |
|:---:|-----|:------:|
${ROWS}"

if [[ -n "$EXTRA_MARKDOWN" ]]; then
  BODY="${BODY}

---

${EXTRA_MARKDOWN}"
fi

BODY="${BODY}

---

<sub>🤖 Generated by **@helpers4** CI • $(date -u +%Y-%m-%d)</sub>"

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  {
    echo "body<<PR_STATUS_COMMENT_EOF"
    echo "$BODY"
    echo "PR_STATUS_COMMENT_EOF"
  } >>"$GITHUB_OUTPUT"
fi

echo "$BODY"
